### ISSUE TITLE
npm install 出错

### ISSUE THREAD

**Issue by cloud-media-forge** [xiaozhu188/electron-vue-cloud-music#26]
![image](https://user-images.githubusercontent.com/3078244/133645430-fe9b6d18-75a6-490b-8587-c945808be147.png)

`cnpm install
✔ Installed 47 packages
✔ Linked 0 latest versions
[1/1] scripts.postinstall test@1.2.3 run "electron-builder install-app-deps", root: "/Users/ghchen/IdeaProjects/electron-vue-cloud-music"
sh: electron-builder: command not found
[npminstall:runscript:error] test@1.2.3 scripts.postinstall run "electron-builder install-app-deps" error: Error [RunScriptError]: Run "sh -c electron-builder install-app-deps" error, exit code 127
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  stdio: [Object],
  exitcode: 127
}
✖ Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c electron-builder install-app-deps" error, exit code 127
RunScriptError: Run "sh -c electron-builder install-app-deps" error, exit code 127
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npminstall version: 5.0.2
npminstall args: /usr/local/Cellar/node/16.8.0/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/Users/ghchen/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://registry.nlark.com

`

**Comment by qhyou** [comment]
我也遇到这样的错误，咋解决的呀哥们儿

**Comment by beautifulwhale** [comment]
可能跟电脑里没有安装electron有关系
您可以去官网安装一下试试

**Comment by woaini521** [comment]
yarn add vue-cli-plugin-electron-builder -D 试一下
